server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profile:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.p2p: DEBUG
  file:
    name: c:/usr/p2p.logs
